language: node_js
node_js:
  - "14.15.0"

install:
  - npm install

branches:
  only:
    - master

before_deploy:
  - yarn build

deploy:
  provider: heroku
  api_key:
    secure: "heroku_api_key"
  app: bring-memories
  on: master
